#
#        ____        _
#       |  _ \      | |
#  _   _| |_) | __ _| | __ _ _ __   ___ ___
# | | | |  _ < / _` | |/ _` | '_ \ / __/ _ \
# | |_| | |_) | (_| | | (_| | | | | (_|  __/
#  \__,_|____/ \__,_|_|\__,_|_| |_|\___\___|
#
# By NoahvdAa
#

General:
  NoAvailableServersMessage: "&cFailed to find server to send you to."

Servers:
  lobby:
    lobby-1:
      weight: 1
      requireOnline: true
      requireSlotsAvailable: true
    lobby-2:
      weight: 1
      requireOnline: true
      requireSlotsAvailable: true
    lobby-3:
      weight: 1
      requireOnline: true
      requireSlotsAvailable: true